### ISSUE TITLE
Bug: Hex Maps Issues

### ISSUE THREAD

**Issue by Cosmic-Lattee** [xaukael/covered-token-rescue-hud#17]
Hello!

I am using the current version of Foundry and this module. When on a hex map it seems to think nearby tokens are in fact under each other. See the picture for an example of what I am talking about.

![image](https://github.com/xaukael/covered-token-rescue-hud/assets/24766235/01832f09-7d5d-406c-ab7c-3a695516dd70)

Also sometimes large red boxes appear around tokens like this below:

![image](https://github.com/xaukael/covered-token-rescue-hud/assets/24766235/f7a3363c-8b92-44ee-9d50-2f6d9d0dcf12)

**Comment by xaukael** [comment]
The red boxes show the bounds of the token. The boxes are that to show where the token hovered in the HUD is located and if the box overlaps with another token's box, it will show in the HUD for either token. The module detects all tokens that have overlapping bounds, which is why they all show. There is no easy way to detect overlapping hexes. If you happen to find a way to do so, I will happily include it.
