### ISSUE TITLE
Foundry error upon hovering over any token

### ISSUE THREAD

**Issue by SecretSquirrel77** [xaukael/covered-token-rescue-hud#4]
Amazing module and an elegant solution to the buried token issue! 
Is there any way to address the error Foundry kicks out whenever I hover over a token? It doesn't seem to break anything, but logs a ton of errors over the course of the session.
![image](https://user-images.githubusercontent.com/77705375/211847103-e8d48759-91b0-4025-959d-a3366d96f0cd.png)

**Comment by xaukael** [comment]
This was brought up in an earlier issue and I am aware of it.

I have been puzzled about what to do about this because there are two ways that I know of to check for the hover psudo, and each throws errors in different environments. Both seem to work despite the error, which is nice, but only adds to my confusion.

I will devote some time to investigating it further tomorrow.

**Comment by xaukael** [comment]
what version of the module are you using?

**Comment by SecretSquirrel77** [comment]
V10
DnD5e (had the error in both the last version and the latest update 2.1.1
Lots of modules, to be fair. I could go through and try to isolate a conflict, like health estimate or token info icons, something that would present information on hover I suppose.

**Comment by SecretSquirrel77** [comment]
Oh, sorry, misread the question. I was on the latest version prior to your release today. 1.0.2?

**Comment by SecretSquirrel77** [comment]
The 1.0.3 update resolved the error on my end. Bravo!

**Comment by xaukael** [comment]
It shouldn't have. 1.0.3 was just an update to fix deprecated properties in the module.json. Like I said, the error is very inconsistent. Version 1.0.4 should fix the issue permanently though.
